frr version 8.4_git
frr defaults traditional
hostname R2-RIP-1
no ipv6 forwarding
!

interface eth1


 ip address 192.168.2.1/24

 no shutdown
!

interface eth2


 ip address 172.17.17.2/30

 no shutdown
!

interface eth3


 ip address 172.17.17.9/30

 no shutdown
!

!







router rip
 version 2


 network 192.168.2.1/24



 network 172.17.17.2/30



 network 172.17.17.9/30


!



!


!

end
