frr version 8.4_git
frr defaults traditional
hostname R2-BGP-1
no ipv6 forwarding
!

interface eth1


 ip address 10.1.1.2/30

 no shutdown
!

interface eth2


 ip address 10.1.1.5/30

 no shutdown
!

!




router bgp 65020

 bgp router-id 10.1.1.2

 no bgp ebgp-requires-policy




 neighbor 10.1.1.1 remote-as 65010

 neighbor 10.1.1.6 remote-as 65030


!







!


!

end
