frr version 8.4_git
frr defaults traditional
hostname R2-OSPF-1
no ipv6 forwarding
!

interface eth1


 ip address 10.1.1.2/30

 no shutdown
!

interface eth2


 ip address 10.1.1.9/30

 no shutdown
!

interface lo


 ip address 172.22.22.2/32

 no shutdown
!

!





router ospf

 ospf router-id 10.1.1.2

 !



 network 10.1.1.2/30 area 0.0.0.0




 network 10.1.1.9/30 area 0.0.0.1




 network 172.22.22.2/32 area 0.0.0.0


!





!


!

end
