frr version 8.4_git
frr defaults traditional
hostname R4-OSPF-1
no ipv6 forwarding
!

interface eth1


 ip address 192.168.1.1/24

 no shutdown
!

interface eth2


 ip address 10.1.1.10/30

 no shutdown
!

interface lo


 ip address 172.22.22.4/32

 no shutdown
!

!





router ospf

 ospf router-id 192.168.1.1

 !



 network 192.168.1.1/24 area 0.0.0.1




 network 10.1.1.10/30 area 0.0.0.1




 network 172.22.22.4/32 area 0.0.0.0


!





!


!

end
